using Microsoft.CodeAnalysis;
using ParserGenerator.NexusGeneration;

namespace ParserGenerator.IAgsGen;

public static class AgsSettingsHolderGen
{
   public const string SETTINGS_NAMESPACE = "Arcanum.Core.Settings";
   public const string SETTINGS_CLASS_NAME = "AGSSettings";

   /// <summary>
   ///    Generates the holder class containing all generated _Config objects.
   /// </summary>
   public static void GenerateSettingsHolder(
      SourceProductionContext context,
      List<INamedTypeSymbol> generatedClasses)
   {
      var builder = new IndentBuilder();

      AppendUsings(builder);

      AppendClassHeader(builder);

      using (builder.Indent())
      {
         AppendProperties(builder, generatedClasses);
         AppendConstructor(builder);
      }

      AppendClassFooter(builder);

      context.AddSource($"{SETTINGS_CLASS_NAME}.g.cs", builder.ToString());
   }

   private static void AppendProperties(IndentBuilder builder, List<INamedTypeSymbol> classes)
   {
      foreach (var cs in classes)
      {
         var fullNamespace = cs.ContainingNamespace.ToDisplayString();
         var className = cs.Name;
         var configTypeName = $"{className}_Config";

         // Use fully qualified name
         var fullyQualifiedType = $"global::{fullNamespace}.{configTypeName}";

         builder.AppendLine($"public {fullyQualifiedType} {className} {{ get; set; }} = new();");
      }
   }

   private static void AppendConstructor(IndentBuilder builder)
   {
      builder.AppendLine();
      builder.AppendLine($"public {SETTINGS_CLASS_NAME}()");
      builder.AppendLine("{");
      using (builder.Indent())
         builder.AppendLine("InitializeDefaults();");
      builder.AppendLine("}");

      builder.AppendLine();
      builder.AppendLine("partial void InitializeDefaults();");
   }

   private static void AppendClassHeader(IndentBuilder builder)
   {
      builder.AppendLine($"public partial class {SETTINGS_CLASS_NAME}");
      builder.AppendLine("{");
   }

   private static void AppendClassFooter(IndentBuilder builder)
   {
      builder.AppendLine("}");
   }

   private static void AppendUsings(IndentBuilder builder)
   {
      builder.AppendLine("// <auto-generated/>");
      builder.AppendLine("#nullable enable");
      builder.AppendLine();
      builder.AppendLine($"namespace {SETTINGS_NAMESPACE};");
      builder.AppendLine();
   }
}