using Arcanum.Core.CoreSystems.SavingSystem.AGS;

namespace Arcanum.Core.Settings;

// ReSharper disable once InconsistentNaming
public class AGSSettings
{
   public AgsSettings ModifierDataSettings { get; set; } = new();
   public AgsSettings CharacterNameDeclarationAgsSettings { get; set; } = new();
   public AgsSettings AgeAgsSettings { get; set; } = new();
   public AgsSettings VegetationAgsSettings { get; set; } = new();
   public AgsSettings OpinionValueAgsSettings { get; set; } = new();
   public AgsSettings BuildingsManagerAgsSettings { get; set; } = new();
   public AgsSettings TownSetupAgsSettings { get; set; } = new();
   public AgsSettings TopographyAgsSettings { get; set; } = new();
   public AgsSettings BuildingDefinitionAgsSettings { get; set; } = new();
   public AgsSettings BuildingLevelAgsSettings { get; set; } = new();
   public AgsSettings InstitutionPresenceAgsSettings { get; set; } = new();
   public AgsSettings InstitutionStateAgsSettings { get; set; } = new();
   public AgsSettings BuildingAgsSettings { get; set; } = new();
   public AgsSettings ClimateAgsSettings { get; set; } = new();
   public AgsSettings RoadAgsSettings { get; set; } = new();
   public AgsSettings ProvinceAgsSettings { get; set; } = new();
   public AgsSettings AreaAgsSettings { get; set; } = new();
   public AgsSettings RegionAgsSettings { get; set; } = new();
   public AgsSettings SuperRegionAgsSettings { get; set; } = new();
   public AgsSettings ContinentAgsSettings { get; set; } = new();
   public AgsSettings CountryAgsSettings { get; set; } = new();
   public AgsSettings LocationAgsSettings { get; set; } = new();
   public AgsSettings CultureAgsSettings { get; set; } = new();
   public AgsSettings TimedModifierAgsSettings { get; set; } = new() { SkipDefaultValues = false };
   public AgsSettings JominiDateSettings { get; set; } = new();
   public AgsSettings GovernmentStateAgsSettings { get; set; } = new();
   public AgsSettings LocationTemplateDataAgsSettings { get; set; } = new();
   public AgsSettings CultureGroupAgsSettings { get; set; } = new();
   public AgsSettings RawMaterialAgsSettings { get; set; } = new();
   public AgsSettings DemandDataAgsSettings { get; set; } = new();
   public AgsSettings PopsDemandDataAgsSettings { get; set; } = new();
   public AgsSettings MapMovementAssistAgsSettings { get; set; } = new();
   public AgsSettings StaticModifierAgsSettings { get; set; } = new();
   public AgsSettings RulerTermAgsSettings { get; set; } = new();
   public AgsSettings ReligionAgsSettings { get; set; } = new();
   public AgsSettings ReligionGroupAgsSettings { get; set; } = new();
   public AgsSettings Eu5ObjOpinionValueAgsSettings { get; set; } = new();
   public AgsSettings ReligiousFactionAgsSettings { get; set; } = new();
   public AgsSettings ReligiousFocusAgsSettings { get; set; } = new();
   public AgsSettings DesignateHeirReasonAgsSettings { get; set; } = new();
   public AgsSettings TraitAgsSettings { get; set; } = new();
   public AgsSettings ParliamentTypeAgsSettings { get; set; } = new();
   public AgsSettings DynastyAgsSettings { get; set; } = new();
   public AgsSettings EstateAgsSettings { get; set; } = new();
   public AgsSettings EnactedLawAgsSettings { get; set; } = new();
   public AgsSettings InstitutionAgsSettings { get; set; } = new();
   public AgsSettings ArtistTypeAgsSettings { get; set; } = new();
   public AgsSettings ModValInstanceAgsSettings { get; set; } = new();
   public AgsSettings EstateCountDefinitonAgsSettings { get; set; } = new();
   public AgsSettings RegnalNumberAgsSettings { get; set; } = new();
   public AgsSettings CountryRankAgsSettings { get; set; } = new();
   public AgsSettings ParliamentDefinitionAgsSettings { get; set; } = new();
   public AgsSettings ReligiousSchoolRelationsAgsSettings { get; set; } = new();
   public AgsSettings CountryDefinitionAgsSettings { get; set; } = new();
   public AgsSettings RegencyAgsSettings { get; set; } = new();
   public AgsSettings MarketAgsSettings { get; set; } = new();
   public AgsSettings LocationRankAgsSettings { get; set; } = new();
   public AgsSettings LanguageAgsSettings { get; set; } = new();
   public AgsSettings CharacterAgsSettings { get; set; } = new();
   public AgsSettings ReligiousSchoolAgsSettings { get; set; } = new();
   public AgsSettings ReligiousSchoolOpinionValueAgsSettings { get; set; } = new();
   public AgsSettings PopTypeAgsSettings { get; set; } = new();
   public AgsSettings PopDefinitionAgsSettings { get; set; } = new();
   public AgsSettings SoundTollAgsSettings { get; set; } = new();
   public AgsSettings DefaultMapDefinitionAgsSettings { get; set; } = new();
   public AgsSettings EstateAttributeDefinitionAgsSettings { get; set; } = new();
   public AgsSettings EstateSatisfactionDefinitionAgsSettings { get; set; } = new();
}