using System.Text;
using Microsoft.CodeAnalysis;

namespace ParserGenerator.HelperClasses;

public static class EnumIndexGenerator
{
   private const string FLAGS_ATTRIBUTE = "System.FlagsAttribute";
   private const string HINT_NAME = "EnumAgsRegistry.g.cs";

   public static void RunEnumIndexGenerator(SourceProductionContext context,
                                            Dictionary<string, EnumAnalysisResult> cache)
   {
      // If the cache is empty, there's nothing to generate.
      if (!cache.Any())
         return;

      context.AddSource(HINT_NAME, GenerateRegistryClass(cache));
   }

   private static string GenerateRegistryClass(IReadOnlyDictionary<string, EnumAnalysisResult> cache)
   {
      var sb = new StringBuilder();

      // --- File Header ---
      sb.AppendLine("// <auto-generated/>");
      sb.AppendLine("#nullable enable");
      sb.AppendLine("using System;");
      sb.AppendLine("using System.Collections.Generic;");
      sb.AppendLine("using System.Collections.ObjectModel;");
      sb.AppendLine("using Arcanum.Core.CoreSystems.SavingSystem.AGS;");
      sb.AppendLine();

      // --- Namespace and Class Definition ---
      sb.AppendLine("namespace Arcanum.Core.AgsRegistry");
      sb.AppendLine("{");

      // --- The main Registry class ---
      sb.AppendLine("    /// <summary>");
      sb.AppendLine("    /// Provides a centralized, runtime registry for enum serialization metadata.");
      sb.AppendLine("    /// </summary>");
      sb.AppendLine("    public static class EnumAgsRegistry");
      sb.AppendLine("    {");
      sb.AppendLine("        private static readonly Dictionary<Type, EnumDataInfo> _registry;");
      sb.AppendLine();
      sb.AppendLine("        public static IReadOnlyDictionary<Type, EnumDataInfo> Registry => _registry;");
      sb.AppendLine();
      sb.AppendLine("        static EnumAgsRegistry()");
      sb.AppendLine("        {");
      sb.AppendLine("            _registry = new Dictionary<Type, EnumDataInfo>");
      sb.AppendLine("            {");

      foreach (var value in cache.Values)
      {
         if (!value.IsValid)
            continue;

         var enumFullName = value.EnumSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

         var isFlags = value.EnumSymbol.GetAttributeForKey(FLAGS_ATTRIBUTE) != null;

         sb.AppendLine($"                [typeof({enumFullName})] = new EnumDataInfo");
         sb.AppendLine("                {");
         sb.AppendLine($"                    EnumType = typeof({enumFullName}),");
         sb.AppendLine($"                    IsFlags = {isFlags.ToString().ToLower()},");
         sb.AppendLine("                    Mapping = new Dictionary<string, string>(new Dictionary<string, string>");
         sb.AppendLine("                    {");

         foreach (var fieldResult in value.FieldResults)
         {
            if (!fieldResult.IsValid || fieldResult.IsIgnored)
               continue;

            var fieldName = fieldResult.FieldSymbol.Name;
            var serialKey = fieldResult.Key;
            sb.AppendLine($"                        {{ \"{fieldName}\", \"{serialKey}\" }},");
         }

         sb.AppendLine("                    })"); // End of new Dictionary
         sb.AppendLine("                },"); // End of new EnumDataInfo
      }

      sb.AppendLine("            };"); // End of _registry initialization
      sb.AppendLine("        }"); // End of static constructor
      sb.AppendLine("    }"); // End of class
      sb.AppendLine("}"); // End of namespace

      return sb.ToString();
   }
}