using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace ParserGenerator.HelperClasses;

public static class NexusHelpers
{
   private const string INEXUS_INTERFACE = "Nexus.Core.INexus";

   private const string READONLY_NEXUS_ATTRIBUTE_NAME =
      "Arcanum.Core.CoreSystems.NUI.Attributes.ReadonlyNexusAttribute";

   private const string NEXUS_CORE_CORESYSTEMS_NUI_ATTRIBUTES_BLOCK_EMPTY_ATTRIBUTE =
      "Arcanum.Core.CoreSystems.NUI.Attributes.BlockEmptyAttribute";

   private const string DESCRIPTION_ATTRIBUTE_NAME = "System.ComponentModel.DescriptionAttribute";

   /// <summary>
   /// This transform finds any class that implements INexus.
   /// It's the gatekeeper for both generation steps.
   /// </summary>
   public static INamedTypeSymbol? GetNexusClassSymbol(GeneratorSyntaxContext context, CancellationToken token)
   {
      var classDeclaration = (ClassDeclarationSyntax)context.Node;

      if (ModelExtensions.GetDeclaredSymbol(context.SemanticModel, classDeclaration, token) is INamedTypeSymbol
          classSymbol)
      {
         var nexusInterface = context.SemanticModel.Compilation.GetTypeByMetadataName(INEXUS_INTERFACE);
         if (nexusInterface != null &&
             classSymbol.AllInterfaces.Contains(nexusInterface, SymbolEqualityComparer.Default))
            return classSymbol;
      }

      return null;
   }

   public static void RunPropertyModifierGenerator(INamedTypeSymbol classSymbol, SourceProductionContext context)
   {
      var sourceCode = GeneratePropertyModifierPart(classSymbol, Helpers.FindModifiableMembers(classSymbol, context));
      var hintName = $"{classSymbol.ContainingNamespace}.{classSymbol.Name}.PropertyModifier.g.cs";
      context.AddSource(hintName, sourceCode);
   }

   private static string GeneratePropertyModifierPart(INamedTypeSymbol classSymbol, List<ISymbol> members)
   {
      var readonlyStatuses = new List<bool>();
      var allowsEmpty = new List<bool>();
      var descriptions = new List<string?>();

      // List of all members that are a collection
      var collectionMembers = new List<ISymbol>();

      var namespaceName = classSymbol.ContainingNamespace.ToDisplayString();
      var className = classSymbol.Name;

      var builder = new StringBuilder();
      builder.AppendLine("// <auto-generated/>");
      builder.AppendLine("#nullable enable");
      builder.AppendLine("using Nexus.Core;");
      builder.AppendLine("using System.Runtime.CompilerServices;");
      builder.AppendLine("using System.ComponentModel;");
#if DEBUG
      builder.AppendLine("using System.Diagnostics;");
#endif
      builder.AppendLine($"namespace {namespaceName};");
      builder.AppendLine();
      builder.AppendLine($"public partial class {className}");
      builder.AppendLine("{");

      // 1. Generate the Enum
      builder.AppendLine("    public enum Field");
      builder.AppendLine("    {");
      foreach (var member in members)
      {
         var memberType = member switch
         {
            IPropertySymbol p => p.Type,
            IFieldSymbol f => f.Type,
            _ => throw new ArgumentOutOfRangeException(),
         };

         // Gather the readonly status
         readonlyStatuses.Add(member.GetAttributes()
                                    .Any(ad => string.Equals(ad.AttributeClass?.ToDisplayString(),
                                                             READONLY_NEXUS_ATTRIBUTE_NAME,
                                                             StringComparison.Ordinal)));
         // Gather the AllowsEmpty status
         allowsEmpty.Add(!member.GetAttributes()
                                .Any(ad => string.Equals(ad.AttributeClass?.ToDisplayString(),
                                                         NEXUS_CORE_CORESYSTEMS_NUI_ATTRIBUTES_BLOCK_EMPTY_ATTRIBUTE,
                                                         StringComparison.Ordinal)));

         // Gather the description (if any)
         var descriptionAttribute = member.GetAttributes()
                                          .FirstOrDefault(ad =>
                                                             string.Equals(ad.AttributeClass?.ToDisplayString(),
                                                                           DESCRIPTION_ATTRIBUTE_NAME,
                                                                           StringComparison.Ordinal));
         // ReSharper disable once MergeIntoPattern
         descriptions.Add(descriptionAttribute is null
                             ? null
                             : descriptionAttribute.ConstructorArguments.Length == 1 &&
                               descriptionAttribute.ConstructorArguments[0].Value is string desc
                                ? desc
                                : null);

         if (memberType.AllInterfaces.Any(i => string.Equals(i.ToDisplayString(),
                                                             "System.Collections.IList",
                                                             StringComparison.Ordinal)))
            collectionMembers.Add(member);

         // 2. Get a fully qualified name for the type
         var memberTypeName = memberType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
         builder.AppendLine($"        [ExpectedType(typeof({memberTypeName}))]");
         builder.AppendLine($"        {member.Name},");
      }

      builder.AppendLine("    }");
      builder.AppendLine();

      #region Property Modifiers and acessors

      builder.AppendLine("#region Property Modifier Backing Fields");
      builder.AppendLine();

      // ------- Readonly Array -------
      builder.AppendLine("    /// <summary>");
      builder.AppendLine("    /// A pre-generated array indicating whether a property is read-only.");
      builder.AppendLine("    /// Accessed via the 'Field' enum index.");
      builder.AppendLine("    /// </summary>");

      // Convert the list of booleans to a C# array literal string
      var arrayInitializer = string.Join(", ", readonlyStatuses.Select(s => s.ToString().ToLower()));
      builder.AppendLine($"    private static readonly bool[] _isReadOnly = {{ {arrayInitializer} }};");
      builder.AppendLine();

      // -------- Allows Empty Value Array --------
      builder.AppendLine("    /// <summary>");
      builder.AppendLine("    /// A pre-generated array indicating whether a property allows empty values.");
      builder.AppendLine("    /// Accessed via the 'Field' enum index.");
      builder.AppendLine("    /// </summary>");

      var allowsEmptyInitializer = string.Join(", ", allowsEmpty.Select(s => s.ToString().ToLower()));
      builder.AppendLine($"    private static readonly bool[] _allowsEmpty = {{ {allowsEmptyInitializer} }};");
      builder.AppendLine();

      // -------- Description Array --------
      builder.AppendLine("    /// <summary>");
      builder.AppendLine("    /// A pre-generated array containing the description of each property, if any.");
      builder.AppendLine("    /// Accessed via the 'Field' enum index.");
      builder.AppendLine("    /// </summary>");

      var descriptionInitializer = string.Join(", ",
                                               descriptions.Select(s => s is null
                                                                           ? "null"
                                                                           : SymbolDisplay.FormatLiteral(s, true)));
      builder.AppendLine($"    private static readonly string?[] _descriptions = {{ {descriptionInitializer} }};");
      builder.AppendLine();

      builder.AppendLine("#endregion");
      builder.AppendLine();

      builder.AppendLine("#region Property Modifier Methods");
      builder.AppendLine();

      // --- Generate a public accessor method for the readonly status ---
      builder.AppendLine("    /// <summary>");
      builder.AppendLine("    /// Checks if a property is marked as read-only.");
      builder.AppendLine("    /// </summary>");
      builder.AppendLine("    public bool IsPropertyReadOnly(Enum property)");
      builder.AppendLine("    {");
      builder.AppendLine("        Debug.Assert(Enum.IsDefined(typeof(Field), property), \"Invalid property enum value\");");
      builder.AppendLine("        return _isReadOnly[(int)((Field)property)];");
      builder.AppendLine("    }");
      builder.AppendLine();

      // --- Generate a public accessor method for the AllowsEmpty status ---
      builder.AppendLine("    /// <summary>");
      builder.AppendLine("    /// Checks if a property allows empty values.");
      builder.AppendLine("    /// </summary>");
      builder.AppendLine("    public bool AllowsEmptyValue(Enum property)");
      builder.AppendLine("    {");
      builder.AppendLine("        Debug.Assert(Enum.IsDefined(typeof(Field), property), \"Invalid property enum value\");");
      builder.AppendLine("        return _allowsEmpty[(int)((Field)property)];");
      builder.AppendLine("    }");
      builder.AppendLine();

      // --- Generate a public accessor method for the Description ---
      builder.AppendLine("    /// <summary>");
      builder.AppendLine("    /// Gets the description of a property, if any.");
      builder.AppendLine("    /// </summary>");
      builder.AppendLine("    public string? GetDescription(Enum property)");
      builder.AppendLine("    {");
      builder.AppendLine("        Debug.Assert(Enum.IsDefined(typeof(Field), property), \"Invalid property enum value\");");
      builder.AppendLine("        return _descriptions[(int)((Field)property)];");
      builder.AppendLine("    }");
      builder.AppendLine();

      builder.AppendLine("#endregion");
      builder.AppendLine();

      #endregion

      #region Get and Set Value methods

      // 2. Generate the SetValue method
      builder.AppendLine("    public void _setValue(Enum property, object value)");
      builder.AppendLine("    {");
      // Check if the property is readonly
      builder.AppendLine("        Debug.Assert(!IsPropertyReadOnly(property), \"Attempting to set a readonly property\");");

      builder.AppendLine("        switch (property)");
      builder.AppendLine("        {");
      foreach (var member in members)
      {
         var memberType = member is IPropertySymbol p ? p.Type : ((IFieldSymbol)member).Type;
         var typeName = memberType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
         builder.AppendLine($"            case Field.{member.Name}:");
#if DEBUG
         builder.AppendLine($"                Debug.Assert(value is {typeName}, \"{member.Name} needs to be a {typeName}\");");
#endif
         builder.AppendLine($"                this.{member.Name} = ({typeName})value;");
         builder.AppendLine("                break;");
      }

      builder.AppendLine("        }");
      builder.AppendLine("    }");
      builder.AppendLine();

      // 3. Generate the GetValue method
      //builder.AppendLine("    [PropertyGetter]");
      builder.AppendLine("    public object _getValue(Enum property)");
      builder.AppendLine("    {");
      builder.AppendLine("        switch (property)");
      builder.AppendLine("        {");
      foreach (var member in members)
      {
         builder.AppendLine($"            case Field.{member.Name}:");
         builder.AppendLine($"                return this.{member.Name};");
      }

      builder.AppendLine("            default:");
      builder.AppendLine("                throw new ArgumentOutOfRangeException(nameof(property));");
      builder.AppendLine("        }");
      builder.AppendLine("    }");

      #endregion

      #region Collection Manipulation Methods

      builder.AppendLine();
      builder.AppendLine("#region Collection Manipulation Methods");
      builder.AppendLine();

      // --- AddToCollection ---
      builder.AppendLine("    public void _addToCollection(Enum property, object item)");
      builder.AppendLine("    {");
      builder.AppendLine("        switch (property)");
      builder.AppendLine("        {");
      foreach (var member in collectionMembers)
      {
         var memberType = member is IPropertySymbol p ? p.Type : ((IFieldSymbol)member).Type;
         // Get the collection's item type, e.g., 'string' from 'ObservableRangeCollection<string>'
         var itemType = (memberType as INamedTypeSymbol)?.TypeArguments.FirstOrDefault();
         var itemTypeName = itemType?.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat) ?? "object";

         builder.AppendLine($"            case Field.{member.Name}:");
         builder.AppendLine($"                Debug.Assert(item is {itemTypeName}, \"Item needs to be a {itemTypeName}\");");
         builder.AppendLine($"                Debug.Assert(this.{member.Name} is System.Collections.Generic.ICollection<{itemTypeName}>, \"Property '{member.Name}' is not a collection.\");");
         builder.AppendLine($"                if (this.{member.Name} is System.Collections.Generic.ICollection<{itemTypeName}> {member.Name}_coll && item is {itemTypeName} {member.Name}_typedItem)");
         builder.AppendLine($"                    {member.Name}_coll.Add({member.Name}_typedItem);");
         builder.AppendLine("                break;");
      }

      builder.AppendLine("            default:");
      builder.AppendLine("                throw new InvalidOperationException($\"Property '{property}' is not a collection.\");");
      builder.AppendLine("        }");
      builder.AppendLine("    }");
      builder.AppendLine();

      // --- RemoveFromCollection ---
      builder.AppendLine("    public void _removeFromCollection(Enum property, object item)");
      builder.AppendLine("    {");
      builder.AppendLine("        switch (property)");
      builder.AppendLine("        {");
      foreach (var member in collectionMembers)
      {
         var memberType = member is IPropertySymbol p ? p.Type : ((IFieldSymbol)member).Type;
         var itemType = (memberType as INamedTypeSymbol)?.TypeArguments.FirstOrDefault();
         var itemTypeName = itemType?.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat) ?? "object";

         builder.AppendLine($"            case Field.{member.Name}:");
         builder.AppendLine($"                Debug.Assert(item is {itemTypeName}, \"Item needs to be a {itemTypeName}\");");
         builder.AppendLine($"                Debug.Assert(this.{member.Name} is System.Collections.Generic.ICollection<{itemTypeName}>, \"Property '{member.Name}' is not a collection.\");");
         builder.AppendLine($"                if (this.{member.Name} is System.Collections.Generic.ICollection<{itemTypeName}> {member.Name}_coll && item is {itemTypeName} {member.Name}_typedItem)");
         builder.AppendLine($"                    {member.Name}_coll.Remove({member.Name}_typedItem);");
         builder.AppendLine("                break;");
      }

      builder.AppendLine("            default:");
      builder.AppendLine("                throw new InvalidOperationException($\"Property '{property}' is not a collection.\");");
      builder.AppendLine("        }");
      builder.AppendLine("    }");
      builder.AppendLine();

      // --- ClearCollection ---
      builder.AppendLine("    public void _clearCollection(Enum property)");
      builder.AppendLine("    {");
      builder.AppendLine("        switch (property)");
      builder.AppendLine("        {");
      foreach (var member in collectionMembers)
      {
         var memberType = (member is IPropertySymbol p) ? p.Type : ((IFieldSymbol)member).Type;
         var itemType = (memberType as INamedTypeSymbol)?.TypeArguments.FirstOrDefault();
         var itemTypeName = itemType?.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat) ?? "object";

         builder.AppendLine($"            case Field.{member.Name}:");
         builder.AppendLine($"                Debug.Assert(this.{member.Name} is System.Collections.Generic.ICollection<{itemTypeName}>, \"Property '{member.Name}' is not a collection.\");");
         builder.AppendLine($"                if (this.{member.Name} is System.Collections.Generic.ICollection<{itemTypeName}> {member.Name}_coll)");
         builder.AppendLine($"                    {member.Name}_coll.Clear();");
         builder.AppendLine("                break;");
      }

      builder.AppendLine("            default:");
      builder.AppendLine("                throw new InvalidOperationException($\"Property '{property}' is not a collection.\");");
      builder.AppendLine("        }");
      builder.AppendLine("    }");
      builder.AppendLine();

      builder.AppendLine("#endregion");
      builder.AppendLine();

      #endregion

      #region Indexer

      // 4. Generate the indexer
      builder.AppendLine();
      builder.AppendLine("    public object this[Enum key]");
      builder.AppendLine("    {");
      builder.AppendLine("        get {");
      builder.AppendLine("            object value = null!;");
      builder.AppendLine("            Nx.ForceGet(this, key, ref value);");
      builder.AppendLine("            return value;");
      builder.AppendLine("        }");
      builder.AppendLine("        set => Nx.ForceSet(value, this, key);");
      builder.AppendLine("    }");

      #endregion

      #region GetAllProperties

      builder.AppendLine();
      builder.AppendLine("    public List<Enum> GetAllProperties()");
      builder.AppendLine("    {");
      builder.AppendLine("        return Enum.GetValues(typeof(Field)).Cast<Enum>().ToList();");
      builder.AppendLine("    }");

      #endregion

      #region Property Changed

      builder.AppendLine();
      builder.AppendLine("#region INotifyPropertyChanged Implementation");
      builder.AppendLine();
      builder.AppendLine("    public event PropertyChangedEventHandler? PropertyChanged;");
      builder.AppendLine();
      builder.AppendLine("    protected virtual void OnPropertyChanged([CallerMemberName] string? propertyName = null)");
      builder.AppendLine("    {");
      builder.AppendLine("        PropertyChanged?.Invoke(this, new(propertyName));");
      builder.AppendLine("    }");
      builder.AppendLine();
      builder.AppendLine("    protected bool SetField<T>(ref T field, T value, [CallerMemberName] string? propertyName = null)");
      builder.AppendLine("    {");
      builder.AppendLine("        if (EqualityComparer<T>.Default.Equals(field, value))");
      builder.AppendLine("            return false;");
      builder.AppendLine();
      builder.AppendLine("        field = value;");
      builder.AppendLine("        OnPropertyChanged(propertyName);");
      builder.AppendLine("        return true;");
      builder.AppendLine("    }");
      builder.AppendLine();
      builder.AppendLine("#endregion");
      builder.AppendLine();

      #endregion

      builder.AppendLine("}"); // Close class

      return builder.ToString();
   }
}